### PR TITLE
Creation Foundation project

### PR DESCRIPTION
**Pull request by FDGalarza**
The Foundation project is created

### CODE REVIEW

**Review by FDGalarza — COMMENTED** [review]
the chnges are approved

**Comment by FDGalarza** [comment]
approved

**Review by jorgeolarte — CHANGES_REQUESTED** [review]
When I tried to run locally but unfortunately we have this problem

`Failed to resolve import "./App.jsx" from "src/main.jsx". Does the file exist?`

**Review by jorgeolarte — APPROVED** [review]
LGTM

**Pull request merged**
